apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "homeassistant.name" . }}
    chart: {{ template "homeassistant.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.server.name }}
  name: {{ template "homeassistant.server.fullname" . }}-config
data:
{{- range $key, $value := .Values.serverFiles }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}
