apiVersion: v1
kind: Service
metadata:
  name: {{ template "homeassistant.server.fullname" . }}
  labels:
    app: {{ template "homeassistant.name" . }}
    chart: {{ template "homeassistant.chart" . }}
    component: {{ .Values.server.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.server.service.annotations }}
  annotations:
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8123
      protocol: TCP
  selector:
    app: {{ template "homeassistant.name" . }}
    component: {{ .Values.server.name }}
    release: {{ .Release.Name }}
